[package]
name = "encprjct"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rpassword = "7"
ratatui = "0.26"
crossterm = "0.27"
color-eyre = "0.6"
